### ISSUE TITLE
Analizar agregar funcionalidad de actualización de configuración de servidor

### ISSUE THREAD

**Issue by DeveloperOscar** [puyu-pe/puka-csharp#21]
-Modificar algun parametro de configuración , requeriria una nueva instalación , es por ello que se debe agregar funcionalidad para poder actualizar estos parametros, ejm. url de bifrost , namespace

**Comment by OscarDevCPP** [comment]
El proyecto estara descontinuado, y ademas esta funcionalidad no es necesario debido a que en el lado del usuario no deberia de poderse configurar estos parametros
